In [1]:
import pandas as pd
import os

In [2]:
df_val = pd.read_csv('/home/andreafiandro/NAS/val.tsv', sep='\u0001', header=None, nrows=100000)
df_val

FileNotFoundError: [Errno 2] File b'/home/andreafiandro/NAS/val.tsv' does not exist: b'/home/andreafiandro/NAS/val.tsv'

In [ ]:
for chunk in pd.read_csv('/home/andreafiandro/NAS/training.tsv', sep='\u0001', header=None, chunksize=1000000):
    df_in = process_chunk_tsv(chunk)
    
    break

In [7]:
col_names = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
            'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time',
            'User id engaging', 'Follower count engaging', 'Following count engaging', 'Is verified engaging', 'Account creation time engaging',
            'Engagee follows engager']

def clean_col(x):
    if(pd.isna(x)):
        return x
    else:
        return x.replace('\t', '|')
    
def process_chunk_tsv(df, col_to_clean=['Text tokens', 'Hashtags', 'Present media', 'Present links', 'Present domains']):
    df.columns = col_names
    # Convert boolean to 1 / 0
    df['Is verified'] = df['Is verified'].apply(lambda  x: 1 if x else 0)
    df['Is verified engaging'] = df['Is verified engaging'].apply(lambda  x: 1 if x else 0)

    for col in col_to_clean:
        df[col] = df[col].apply(lambda x: clean_col(x))
        df[col] = df[col].fillna(0)
    return df

In [4]:
df_1 = pd.read_csv('/home/andreafiandro/NAS/grouped/{}'.format(files_csv[0]))
print('File {} has {} lines'.format(files_csv[0], df_1.shape[0]))

File training_lgbm_18.csv has 5523757 lines

In [5]:
files_csv.remove(files_csv[0])

In [6]:
def count_item(x):
    if(x != 0):
        return len(x.split('|'))

def aggregate_features(df_input, is_incremental=False):
        if(is_incremental == False): # Se è la prima groupby devo eliminare le colonne inutili
            not_useful_cols = ['User id engaging', 'Account creation time engaging']
            df_input = df_input.drop(not_useful_cols, axis=1)

        if(is_incremental == False):
            if( not self.isval):
                df_input = df_input.rename(columns={'Reply engagement timestamp': 'Reply', 
                                                        'Retweet engagement timestamp': 'Retweet',
                                                        'Retweet with comment engagement timestamp': 'Comment',
                                                        'Like engagement timestamp': 'Like'})


        describing_columns = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
                            'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time']


        df_grouped = df_input.groupby(describing_columns).agg({
            'Follower count engaging': 'mean',
            'Following count engaging': 'mean',
            'Is verified engaging': 'sum',
            'Engagee follows engager': 'sum',
            'Reply': 'count',
            'Retweet': 'count',
            'Comment': 'count',
            'Like': 'count'
        }).reset_index()  


        if(is_incremental == False):
            col_to_count=['Text tokens', 'Hashtags', 'Present media', 'Present links', 'Present domains']

            for col in col_to_count:
                df_grouped[col] = df_grouped[col].apply(lambda x: count_item(x))


        return df_grouped

In [5]:
tot_tweet = 0
for chunk in pd.read_csv('/home/andreafiandro/NAS/val.tsv', sep='\u0001', header=None, chunksize=1000000):
    df_in = process_chunk_tsv(chunk)
    df_in.unique
    break

In [13]:
process_chunk_tsv(chunk)

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,Follower count,Following count,Is verified,Account creation time,User id engaging,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager
0,101|47185|10157|100986|10343|55422|119|14120|1...,NaN,7647B4E9DAF4C1D8973397DC2A04F3E3,Photo,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581703126,8A9AB92B775C62C4AB60DF6773A01571,13941,1216,False,1448292186,0000006C3074607050F1339DDCB890BB,27448,600,False,1520948869,True
1,101|6006|5086|1939|7418|3601|6406|1913|3800|21...,NaN,CCBFBA5AFE7EFC03102EA8D0F86C4208,Photo,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581736431,187AC59639DA9A6F32F7CD118EDD58F7,476439,1478,False,1254447722,00000776B07587ECA9717BFC301F2D6E,102,659,False,1478011810,False
2,101|56898|137|44851|10317|11490|10112|11733|12...,NaN,E18C2DCFC5AF20C650A0FD94598E69B7,Video,NaN,NaN,Retweet,ECED8A16BE2A5E8871FD55F4842F16B1,1582061925,82626B53CB2AD3B469E4AE06EAA9D930,367,702,False,1518708926,00000860E80C67D8C46CE57C64DE9444,230,189,False,1541013180,True
3,101|13497|10437|94005|11161|73632|11067|117|10...,NaN,26DC813FDF8546B757BB9141099F119E,NaN,D58137F9D688C88435FD64FBAEA82B97,E91CDEC8DC7ABF30592FA024616FF970,TopLevel,ECED8A16BE2A5E8871FD55F4842F16B1,1582110043,7AFE06FF54898A1E9C716F539831849E,278,1229,False,1243548061,00000865A1538142CDA5936B07FE4311,65,165,False,1452599043,True
4,101|24781|10152|42041|38268|10301|10798|22497|...,NaN,30A33055566AAC9EB18734C4EAD11FE1,NaN,AEF0CC9FA7B389B9A2ADF1331F00B65B,42DD9E2D4B2C0B0A71E909A6049EC2C2,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581860270,D240DACE38CA84965270C86D47D3BF40,24313527,121,True,1177506290,00000865A1538142CDA5936B07FE4311,64,164,False,1452599043,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,101|12882|97801|10114|10347|30139|14234|24558|...,54DD89D0466F17FCA84238436953A625,6BA5DEBFF1FD5D2B0AF4183E3D17A07B,NaN,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581731299,23156B3620ADE5C501E54D8415AAD76B,2111,1687,True,1250915445,10E5E7CEC8F1C0B5D09EF0093138D4FC,861,718,False,1485398539,False
999996,101|108|42932|14120|131|120|120|188|119|11170|...,5E4DB70D4A248F79A6A944714551391D,9E4D88FEAE1DD5BFB5AD97DD32288B38,Photo,NaN,NaN,TopLevel,B9175601E87101A984A50F8A62A1C374,1582127191,A9897A9225B3EE0EFB26C902EDEFAE58,266552,49185,False,1359050488,10E5E7CEC8F1C0B5D09EF0093138D4FC,861,718,False,1485398539,False
999997,101|108|14255|14120|131|120|120|188|119|11170|...,57BE1846AFA7218785F3A11B582B04C3,9E9210D582063101AE49D92EB7158FB8,Photo,NaN,NaN,TopLevel,B9175601E87101A984A50F8A62A1C374,1581867350,A9897A9225B3EE0EFB26C902EDEFAE58,266552,49185,False,1359050488,10E5E7CEC8F1C0B5D09EF0093138D4FC,861,718,False,1485398539,False
999998,101|91131|10115|10798|10978|10105|10751|160|68...,NaN,AAEA4A9C37E4B079C0DB18C30C5C8AC9,Photo,3A6D1BE2202BA61063B6932801457C9E,BBA1D3359A23689C6783652EA73B12BA,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1582059635,BECE0DD7824D4CFC94714FB2D7950AD4,8154,963,False,1255799510,10E5E7CEC8F1C0B5D09EF0093138D4FC,861,718,False,1485398539,False
999999,101|164|31278|11447|166|11507|90533|32930|1151...,NaN,FB2DCE8FEE1670285C1ABE1A38BAFB12,NaN,2163F1FB4A063FE7D6BCEB3CAF0E39BC,2A0BCE2A876F538FB5C381ECE5AF4BF8,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581774536,2E9E9CF58D517621BF7187CB3E419EAE,1519669,12,False,1366221080,10E5E91C78CDA7855712D10355E0789E,143,494,False,1337010255,False

In [1]:
col_names = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
           'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time',
           'User id engaging', 'Follower count engaging', 'Following count engaging', 'Is verified engaging', 'Account creation time engaging',
           'Engagee follows engager']

def process_chunk_tsv(df):
    df.columns = col_names
    df['Text tokens'] = df['Text tokens'].apply(lambda x: x.replace('\t', '|'))
    return df

In [9]:
process_chunk_tsv(chunk)

ValueError: Length mismatch: Expected axis has 20 elements, new values have 24 elements

In [2]:
col_names = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
           'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time',
           'User id engaging', 'Follower count engaging', 'Following count engaging', 'Is verified engaging', 'Account creation time engaging',
           'Engagee follows engager', 'Reply engagement timestamp', 'Retweet engagement timestamp', 'Retweet with comment engagement timestamp', 'Like engagement timestamp']

def process_chunk_tsv(df):
    df.columns = col_names
    df['Text tokens'] = df['Text tokens'].apply(lambda x: x.replace('\t', '|'))
    return df

In [4]:
chunk_n = 0
for chunk in pd.read_csv('/home/andreafiandro/NAS/training.tsv', sep='\u0001', header=None, chunksize=1000000):
    df_chunk = process_chunk_tsv(chunk)
    break
    df_chunk.to_csv('/home/andreafiandro/NAS/training_chunk_{}.csv'.format(chunk_n), index=False)
    chunk_n += 1

In [10]:
df_gb = df_chunk.groupby('User id engaging').count().reset_index()
df_gb

,User id engaging,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,...,Account creation time,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,0000006C3074607050F1339DDCB890BB,1,0,1,0,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
1,000005C520010F8917EEAB6F5B6EC1C4,1,0,1,1,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
2,000006829BEADA9EEA695CF0C334B426,4,2,4,0,3,3,4,4,4,...,4,4,4,4,4,4,0,0,0,1
3,00000776B07587ECA9717BFC301F2D6E,1,0,1,0,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
4,00000860E80C67D8C46CE57C64DE9444,4,0,4,1,0,0,4,4,4,...,4,4,4,4,4,4,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656111,0DD2A3C795A9F1B6F7567FF25774C68D,2,0,2,0,1,1,2,2,2,...,2,2,2,2,2,2,0,1,0,1
656112,0DD2A774F7679AD1FD5912173D3760FC,1,0,1,0,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
656113,0DD2A7E8AEF35BD0EB83FFA4504F2075,1,0,1,1,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
656114,0DD2A82452C83CD3F825E73498EBD1DE,1,0,1,1,0,0,1,1,1,...,1,1,1,1,1,1,0,0,0,0
656115,0DD2A83B6837B1FA23CEA85748175A46,2,1,2,2,1,1,2,2,2,...,2,2,2,2,2,2,0,1,0,0

In [11]:
df_gb[df_gb['Language'] > 1]

,User id engaging,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,...,Account creation time,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
2,000006829BEADA9EEA695CF0C334B426,4,2,4,0,3,3,4,4,4,...,4,4,4,4,4,4,0,0,0,1
4,00000860E80C67D8C46CE57C64DE9444,4,0,4,1,0,0,4,4,4,...,4,4,4,4,4,4,0,0,0,3
5,0000094443AB46ED4A5C5E201EA3BCAE,3,0,3,0,0,0,3,3,3,...,3,3,3,3,3,3,0,0,0,1
7,00000B85AAF7DE172876FD96718C4469,3,1,3,2,1,1,3,3,3,...,3,3,3,3,3,3,0,3,1,3
10,00000E0C9B364891CDE89ECFC54771DE,4,2,4,2,0,0,4,4,4,...,4,4,4,4,4,4,0,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656100,0DD298A9FE08964E4833CA15424A6FCF,2,0,2,0,0,0,2,2,2,...,2,2,2,2,2,2,0,0,0,1
656104,0DD29C670940549BC84EA760CBE5ACEE,3,0,3,1,0,0,3,3,3,...,3,3,3,3,3,3,0,0,0,2
656110,0DD2A357790C0A7FDB035F322B0FFB23,2,0,2,1,0,0,2,2,2,...,2,2,2,2,2,2,0,0,0,1
656111,0DD2A3C795A9F1B6F7567FF25774C68D,2,0,2,0,1,1,2,2,2,...,2,2,2,2,2,2,0,1,0,1
656115,0DD2A83B6837B1FA23CEA85748175A46,2,1,2,2,1,1,2,2,2,...,2,2,2,2,2,2,0,1,0,0

# Exploratory data analysis

In [58]:
df_input = pd.read_csv('training_chunk_0.csv')
df_input.head()

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,...,User id engaging,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,101|6417|3410|3398|3184|1909|56910|16838|82904...,NaN,D4D1EBDE74F74C5DA529959AF979625C,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581258144,D7EFC6D19CFB09B9A1CE4C4B0E0091F6,...,0000006C3074607050F1339DDCB890BB,27428,600,False,1520948869,False,NaN,NaN,NaN,NaN
1,101|14120|131|120|120|188|119|11170|120|178|71...,NaN,BFB529DAB6D384EB83E899A72AB3830D,Photo,NaN,NaN,TopLevel,B9175601E87101A984A50F8A62A1C374,1581018910,1F30A85E612A24B426013978ADB7AE46,...,000005C520010F8917EEAB6F5B6EC1C4,17,77,False,1569692352,True,NaN,NaN,NaN,NaN
2,101|62342|10858|54439|19571|22480|7831|8129|22...,NaN,519078C7834E9642508F72A6C2D0F3B7,NaN,788ABAA22F1C4A9D186510C1E3E81F58,892B6E0BC037800B59112CFCB95E3301,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581244866,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,2,29,False,1568107028,False,NaN,NaN,NaN,1.581247e+09
3,101|58955|10898|103305|1901|16181|7168|17984|1...,F0F2FBE57F08E7C4326682B5EDA63E3E\tE78674D32346...,52AAE9E33EFAC8C478C57B31A9E31ED1,NaN,C06B84A10A75AE4BF4A102AB45CC2ABF,C0F5328C1D36CD4B34D1808012E18D46,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581250124,BEB3C337B266E2C4769065AD64724329,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN
4,101|2435|5656|2594|8279|8623|1925|64126|14725|...,NaN,89C1298C55EB3D68E2784F0BFB69E6F8,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1580958805,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN

## Preparazione dei dati aggregati per il training

- Raggruppo per le colonne che sono caratteristiche del tweet
- Calcolo i dati aggregati

In [59]:
def clean_col(x):
    if(pd.isna(x)):
        return x
    else:
        return x.replace('\t', '|')
    
col_to_clean=['Hashtags', 'Present media', 'Present links', 'Present domains']


for col in col_to_clean:
    df_input[col] = df_input[col].apply(lambda x: clean_col(x))
    df_input[col] = df_input[col].fillna(0)

In [60]:
df_input.head()

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,...,User id engaging,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,101|6417|3410|3398|3184|1909|56910|16838|82904...,0,D4D1EBDE74F74C5DA529959AF979625C,0,0,0,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581258144,D7EFC6D19CFB09B9A1CE4C4B0E0091F6,...,0000006C3074607050F1339DDCB890BB,27428,600,False,1520948869,False,NaN,NaN,NaN,NaN
1,101|14120|131|120|120|188|119|11170|120|178|71...,0,BFB529DAB6D384EB83E899A72AB3830D,Photo,0,0,TopLevel,B9175601E87101A984A50F8A62A1C374,1581018910,1F30A85E612A24B426013978ADB7AE46,...,000005C520010F8917EEAB6F5B6EC1C4,17,77,False,1569692352,True,NaN,NaN,NaN,NaN
2,101|62342|10858|54439|19571|22480|7831|8129|22...,0,519078C7834E9642508F72A6C2D0F3B7,0,788ABAA22F1C4A9D186510C1E3E81F58,892B6E0BC037800B59112CFCB95E3301,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581244866,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,2,29,False,1568107028,False,NaN,NaN,NaN,1.581247e+09
3,101|58955|10898|103305|1901|16181|7168|17984|1...,F0F2FBE57F08E7C4326682B5EDA63E3E|E78674D323461...,52AAE9E33EFAC8C478C57B31A9E31ED1,0,C06B84A10A75AE4BF4A102AB45CC2ABF,C0F5328C1D36CD4B34D1808012E18D46,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581250124,BEB3C337B266E2C4769065AD64724329,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN
4,101|2435|5656|2594|8279|8623|1925|64126|14725|...,0,89C1298C55EB3D68E2784F0BFB69E6F8,0,0,0,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1580958805,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN

In [55]:
df_input['Is verified'] = df_input['Is verified'].apply(lambda  x: 1 if x else 0)
df_input['Is verified engaging'] = df_input['Is verified engaging'].apply(lambda  x: 1 if x else 0)

In [56]:
not_useful_cols = ['User id engaging', 'Account creation time engaging']

df_input = df_input.drop(not_useful_cols, axis=1)

describing_columns = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
                      'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time']
df_grouped = df_input.groupby(describing_columns).agg({
     'Follower count engaging': 'mean',
     'Following count engaging': 'mean',
     'Is verified engaging': 'sum',
     'Engagee follows engager': 'sum',
     'Reply engagement timestamp': 'count',
     'Retweet engagement timestamp': 'count',
     'Retweet with comment engagement timestamp': 'count',
     'Like engagement timestamp': 'count'
}).reset_index()
df_grouped.head(10)

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,...,Is verified,Account creation time,Follower count engaging,Following count engaging,Is verified engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,101|100035|28088|99890|21127|10815|31886|10950...,0E75B5FA75093B3F1431BA3120784BF4|39FBE25848D4B...,FE4B251A13C6E80999B9C845DF80723B,Photo,AC93BA2EF6B212FDA5BB2FA7BE48F27C,455D10477C02747DE026DD74D1D58DE4,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581205197,CA40F0405BB13DE5B8AB7E7720F8B698,...,0,1234053351,3465.0,4989.0,0,1.0,0,0,0,1
1,101|100061|11273|153|11403|27128|11090|131|714...,ABCB0D1E25EDD5AB767A843716BC4F57,BE3D89C3D1858E302C65932871689826,Photo,CD909CB5FFB5F39F2109EE553058CD5A,1AF4AB6610047165690AACA29B528C64,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581440490,CE4C255DE525CA52498C4FBEDCB7E963,...,1,1220035594,702.0,680.0,0,0.0,0,0,0,0
2,101|100085|24412|10301|13382|10105|137|66103|1...,8FF4D1DAEADC34679AF5FDEEAB651FB4|73BC94E6A33E4...,FD9D49E22E40E079F3B5BE001F58DA36,Photo,E4A87E2467D898C2307288C6A9489644,C003A17394B2835C895F0B79E964C797,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581512424,8032472DA9C6C18EF4B71E4D0F7870CF,...,1,1212249416,691.0,543.0,0,0.0,0,0,0,0
3,101|10011|17342|113|137|36448|10330|12022|1173...,E302A1B2C8246FCED65271E0CCA524DD|A6A2598D68372...,9ED407239B021D385E93A6A12B6A2302,Photo|Photo,0039DF64CA6D4C3E587CF403B337DBEA,FCA72262B99BB78F010B25C882A0C93C,TopLevel,125C57F4FA6D4E110983FB11B52EFD4E,1580995408,F760512F6D7766F1479700F7AC8D5B6E,...,0,1537968370,2.0,54.0,0,0.0,0,0,0,0
4,101|100154|10570|10612|169|16719|10109|58787|4...,FEA2B0801B60352465309D1B7CD770D2,42BE939B4C5D871DB113F04C00CE3316,GIF,B0F684910323929551202A26D3E4A133,65573CE3B1D4382059A442937A45BEAF,TopLevel,06D61DCBBE938971E1EA0C38BD9B5446,1581069840,1BBE3D6DB970389FCFF438ECEC3CCC5A,...,1,1356261655,33.0,191.0,0,0.0,0,0,0,0
5,101|100154|19494|55645|60188|25155|10110|10306...,BFCFBEF4CD9DF9712FD67D8CF4758191,E3F82A10E5A918A3299FE0950EDB0358,Photo,6A0540FED243980F63AD258CD5136BEE,9E34EBC679CA0BC677D198BEE3E37113,TopLevel,06D61DCBBE938971E1EA0C38BD9B5446,1581099604,24AE6B90ECAC288FB5489822AB6879AB,...,1,1368279417,65.0,961.0,0,0.0,0,0,0,0
6,101|100207|15417|55859|11537|119|144|98348|117...,2FBDE8C504949DD1BEB78FAB59381AD7|DE0150E2B1B2D...,7216C4CC7E5071DE51E615A082161AC7,Photo,56311C8EC638222A236FEA02B1C43110,E65788331FE74C7BF62A74C6EDD032D6,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581142424,C7F7C809415F91C8DF1710BEBE0A58FD,...,0,1459653345,404.0,568.0,0,1.0,0,0,0,0
7,101|100355|10246|10146|10160|102913|10149|1544...,1F7EEFEEB735C95C7CFF7ACB23BFDEC2,C0E48C6A699119415773A48CAFD3F1D7,Photo|Photo|Photo|Photo,E0F2ECAAE343DA7EFE8C002CB3F161FE,9B1BD1B658A2DC9B858DBAC6CC921E89,TopLevel,ECED8A16BE2A5E8871FD55F4842F16B1,1581039267,BCDC7E16708AC5B155BA52460DFF687F,...,1,1370489160,159.0,440.0,0,0.0,0,0,0,0
8,101|100393|13028|11639|10812|27170|10341|10531...,32A4138D86700940E38309850BBA0B96,8E833945E742361F6E862A3DE648B0A1,Photo,2DAC1FCC1BA255561902170E356957F2,3896E26D12C903F0A00B6B1BE9A9BEA3,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581379263,5BB54F9D5D2BDBCB88D6117296190C3E,...,1,1205460864,1895.0,2091.0,0,1.0,0,0,0,0
9,101|100397|10731|92795|10266|69248|14328|18331...,27A7A235BC6F182ED13C6FC3405D74F5|3F9FD29C893ED...,0FB3067DEE51F9FE2F4C61538FAA4F1A,Photo,2E6A486C7803ADEA8EBD2FA32129CEC4,3896E26D12C903F0A00B6B1BE9A9BEA3,TopLevel,ECED8A16BE2A5E8871FD55F4842F16B1,1581450373,AC15E2840C6390BB45F0FF8DB7546D47,...,1,1272051098,652.0,449.0,0,0.0,0,0,0,0

In [62]:
def count_item(x):
    if(x != 0):
        return len(x.split('|'))

In [63]:
col_to_count=['Text tokens', 'Hashtags', 'Present media', 'Present links', 'Present domains']
for col in col_to_count:
    df_grouped[col] = df_grouped[col].apply(lambda x: count_item(x))
df_grouped.head()

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,...,Is verified,Account creation time,Follower count engaging,Following count engaging,Is verified engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,57,2,FE4B251A13C6E80999B9C845DF80723B,1,1,1,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581205197,CA40F0405BB13DE5B8AB7E7720F8B698,...,0,1234053351,3465.0,4989.0,0,1.0,0,0,0,1
1,94,1,BE3D89C3D1858E302C65932871689826,1,1,1,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581440490,CE4C255DE525CA52498C4FBEDCB7E963,...,1,1220035594,702.0,680.0,0,0.0,0,0,0,0
2,73,3,FD9D49E22E40E079F3B5BE001F58DA36,1,1,1,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581512424,8032472DA9C6C18EF4B71E4D0F7870CF,...,1,1212249416,691.0,543.0,0,0.0,0,0,0,0
3,98,6,9ED407239B021D385E93A6A12B6A2302,2,1,1,TopLevel,125C57F4FA6D4E110983FB11B52EFD4E,1580995408,F760512F6D7766F1479700F7AC8D5B6E,...,0,1537968370,2.0,54.0,0,0.0,0,0,0,0
4,58,1,42BE939B4C5D871DB113F04C00CE3316,1,1,1,TopLevel,06D61DCBBE938971E1EA0C38BD9B5446,1581069840,1BBE3D6DB970389FCFF438ECEC3CCC5A,...,1,1356261655,33.0,191.0,0,0.0,0,0,0,0

# Lettura con dask

In [1]:
import dask.dataframe as dd
from dask.diagnostics import ProgressBar
ProgressBar().register()

In [2]:
col_names = ['Text tokens', 'Hashtags', 'Tweet id', 'Present media', 'Present links', 'Present domains', 'Tweet type', 'Language', 'Timestamp',
            'User id', 'Follower count', 'Following count', 'Is verified', 'Account creation time',
            'User id engaging', 'Follower count engaging', 'Following count engaging', 'Is verified engaging', 'Account creation time engaging',
            'Engagee follows engager', 'Reply engagement timestamp', 'Retweet engagement timestamp', 'Retweet with comment engagement timestamp', 'Like engagement timestamp']

In [3]:
dd_training = dd.read_csv('/home/andreafiandro/NAS/training.tsv', sep='\u0001', header=None)
dd_training.columns = col_names
dd_training.head()

[########################################] | 100% Completed |  6.5s

,Text tokens,Hashtags,Tweet id,Present media,Present links,Present domains,Tweet type,Language,Timestamp,User id,...,User id engaging,Follower count engaging,Following count engaging,Is verified engaging,Account creation time engaging,Engagee follows engager,Reply engagement timestamp,Retweet engagement timestamp,Retweet with comment engagement timestamp,Like engagement timestamp
0,101\t6417\t3410\t3398\t3184\t1909\t56910\t1683...,NaN,D4D1EBDE74F74C5DA529959AF979625C,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581258144,D7EFC6D19CFB09B9A1CE4C4B0E0091F6,...,0000006C3074607050F1339DDCB890BB,27428,600,False,1520948869,False,NaN,NaN,NaN,NaN
1,101\t14120\t131\t120\t120\t188\t119\t11170\t12...,NaN,BFB529DAB6D384EB83E899A72AB3830D,Photo,NaN,NaN,TopLevel,B9175601E87101A984A50F8A62A1C374,1581018910,1F30A85E612A24B426013978ADB7AE46,...,000005C520010F8917EEAB6F5B6EC1C4,17,77,False,1569692352,True,NaN,NaN,NaN,NaN
2,101\t62342\t10858\t54439\t19571\t22480\t7831\t...,NaN,519078C7834E9642508F72A6C2D0F3B7,NaN,788ABAA22F1C4A9D186510C1E3E81F58,892B6E0BC037800B59112CFCB95E3301,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581244866,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,2,29,False,1568107028,False,NaN,NaN,NaN,1.581247e+09
3,101\t58955\t10898\t103305\t1901\t16181\t7168\t...,F0F2FBE57F08E7C4326682B5EDA63E3E\tE78674D32346...,52AAE9E33EFAC8C478C57B31A9E31ED1,NaN,C06B84A10A75AE4BF4A102AB45CC2ABF,C0F5328C1D36CD4B34D1808012E18D46,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581250124,BEB3C337B266E2C4769065AD64724329,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN
4,101\t2435\t5656\t2594\t8279\t8623\t1925\t64126...,NaN,89C1298C55EB3D68E2784F0BFB69E6F8,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1580958805,9E1FD934C376903895DEEBCC0F6AB920,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN

In [4]:
a = dd_training.shape
a[0].compute(),a[1]

[                                        ] | 0% Completed |  1min 10.0s

KeyboardInterrupt:

In [ ]:
n_tweets = dd_training['Tweet id'].drop_duplicates().compute()
n_tweets

[###################################     ] | 88% Completed |  1hr 41min 36.4s